#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Goat")]
public partial class GoatDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertADMIN(ADMIN instance);
  partial void UpdateADMIN(ADMIN instance);
  partial void DeleteADMIN(ADMIN instance);
  partial void InsertSUGGESTION(SUGGESTION instance);
  partial void UpdateSUGGESTION(SUGGESTION instance);
  partial void DeleteSUGGESTION(SUGGESTION instance);
  partial void InsertUSER(USER instance);
  partial void UpdateUSER(USER instance);
  partial void DeleteUSER(USER instance);
  partial void InsertUSER_PROFILE(USER_PROFILE instance);
  partial void UpdateUSER_PROFILE(USER_PROFILE instance);
  partial void DeleteUSER_PROFILE(USER_PROFILE instance);
  partial void InsertREF_USER_HOUSEINFO(REF_USER_HOUSEINFO instance);
  partial void UpdateREF_USER_HOUSEINFO(REF_USER_HOUSEINFO instance);
  partial void DeleteREF_USER_HOUSEINFO(REF_USER_HOUSEINFO instance);
  partial void InsertHOUSE_INFO(HOUSE_INFO instance);
  partial void UpdateHOUSE_INFO(HOUSE_INFO instance);
  partial void DeleteHOUSE_INFO(HOUSE_INFO instance);
  partial void InsertCOMMENT(COMMENT instance);
  partial void UpdateCOMMENT(COMMENT instance);
  partial void DeleteCOMMENT(COMMENT instance);
  partial void InsertCOLLECCTION(COLLECCTION instance);
  partial void UpdateCOLLECCTION(COLLECCTION instance);
  partial void DeleteCOLLECCTION(COLLECCTION instance);
  partial void InsertHOUSE_ORDER(HOUSE_ORDER instance);
  partial void UpdateHOUSE_ORDER(HOUSE_ORDER instance);
  partial void DeleteHOUSE_ORDER(HOUSE_ORDER instance);
  #endregion
	
	public GoatDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GoatConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public GoatDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public GoatDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public GoatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public GoatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ADMIN> ADMIN
	{
		get
		{
			return this.GetTable<ADMIN>();
		}
	}
	
	public System.Data.Linq.Table<SUGGESTION> SUGGESTION
	{
		get
		{
			return this.GetTable<SUGGESTION>();
		}
	}
	
	public System.Data.Linq.Table<USER> USER
	{
		get
		{
			return this.GetTable<USER>();
		}
	}
	
	public System.Data.Linq.Table<USER_PROFILE> USER_PROFILE
	{
		get
		{
			return this.GetTable<USER_PROFILE>();
		}
	}
	
	public System.Data.Linq.Table<REF_USER_HOUSEINFO> REF_USER_HOUSEINFO
	{
		get
		{
			return this.GetTable<REF_USER_HOUSEINFO>();
		}
	}
	
	public System.Data.Linq.Table<HOUSE_INFO> HOUSE_INFO
	{
		get
		{
			return this.GetTable<HOUSE_INFO>();
		}
	}
	
	public System.Data.Linq.Table<COMMENT> COMMENT
	{
		get
		{
			return this.GetTable<COMMENT>();
		}
	}
	
	public System.Data.Linq.Table<COLLECCTION> COLLECCTION
	{
		get
		{
			return this.GetTable<COLLECCTION>();
		}
	}
	
	public System.Data.Linq.Table<HOUSE_ORDER> HOUSE_ORDER
	{
		get
		{
			return this.GetTable<HOUSE_ORDER>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _adminId;
	
	private string _password;
	
	private string _name;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadminIdChanging(int value);
    partial void OnadminIdChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
	
	public ADMIN()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int adminId
	{
		get
		{
			return this._adminId;
		}
		set
		{
			if ((this._adminId != value))
			{
				this.OnadminIdChanging(value);
				this.SendPropertyChanging();
				this._adminId = value;
				this.SendPropertyChanged("adminId");
				this.OnadminIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SUGGESTION")]
public partial class SUGGESTION : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _suggestionId;
	
	private string _suggestionContent;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsuggestionIdChanging(int value);
    partial void OnsuggestionIdChanged();
    partial void OnsuggestionContentChanging(string value);
    partial void OnsuggestionContentChanged();
    #endregion
	
	public SUGGESTION()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suggestionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int suggestionId
	{
		get
		{
			return this._suggestionId;
		}
		set
		{
			if ((this._suggestionId != value))
			{
				this.OnsuggestionIdChanging(value);
				this.SendPropertyChanging();
				this._suggestionId = value;
				this.SendPropertyChanged("suggestionId");
				this.OnsuggestionIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suggestionContent", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string suggestionContent
	{
		get
		{
			return this._suggestionContent;
		}
		set
		{
			if ((this._suggestionContent != value))
			{
				this.OnsuggestionContentChanging(value);
				this.SendPropertyChanging();
				this._suggestionContent = value;
				this.SendPropertyChanged("suggestionContent");
				this.OnsuggestionContentChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[USER]")]
public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _userId;
	
	private string _phone;
	
	private string _password;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
	
	public USER()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int userId
	{
		get
		{
			return this._userId;
		}
		set
		{
			if ((this._userId != value))
			{
				this.OnuserIdChanging(value);
				this.SendPropertyChanging();
				this._userId = value;
				this.SendPropertyChanged("userId");
				this.OnuserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(24) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USER_PROFILE")]
public partial class USER_PROFILE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _userId;
	
	private string _userName;
	
	private string _headImage;
	
	private System.Nullable<int> _gender;
	
	private string _birth;
	
	private string _email;
	
	private string _description;
	
	private string _phone;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnheadImageChanging(string value);
    partial void OnheadImageChanged();
    partial void OngenderChanging(System.Nullable<int> value);
    partial void OngenderChanged();
    partial void OnbirthChanging(string value);
    partial void OnbirthChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
	
	public USER_PROFILE()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int userId
	{
		get
		{
			return this._userId;
		}
		set
		{
			if ((this._userId != value))
			{
				this.OnuserIdChanging(value);
				this.SendPropertyChanging();
				this._userId = value;
				this.SendPropertyChanged("userId");
				this.OnuserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(50)")]
	public string userName
	{
		get
		{
			return this._userName;
		}
		set
		{
			if ((this._userName != value))
			{
				this.OnuserNameChanging(value);
				this.SendPropertyChanging();
				this._userName = value;
				this.SendPropertyChanged("userName");
				this.OnuserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headImage", DbType="VarChar(50)")]
	public string headImage
	{
		get
		{
			return this._headImage;
		}
		set
		{
			if ((this._headImage != value))
			{
				this.OnheadImageChanging(value);
				this.SendPropertyChanging();
				this._headImage = value;
				this.SendPropertyChanged("headImage");
				this.OnheadImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Int")]
	public System.Nullable<int> gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth", DbType="VarChar(50)")]
	public string birth
	{
		get
		{
			return this._birth;
		}
		set
		{
			if ((this._birth != value))
			{
				this.OnbirthChanging(value);
				this.SendPropertyChanging();
				this._birth = value;
				this.SendPropertyChanged("birth");
				this.OnbirthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(11)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REF_USER_HOUSEINFO")]
public partial class REF_USER_HOUSEINFO : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _refId;
	
	private System.Nullable<int> _userId;
	
	private System.Nullable<int> _houseId;
	
	private System.Nullable<int> _step;
	
	private System.Nullable<int> _price;
	
	private System.Nullable<int> _state;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrefIdChanging(int value);
    partial void OnrefIdChanged();
    partial void OnuserIdChanging(System.Nullable<int> value);
    partial void OnuserIdChanged();
    partial void OnhouseIdChanging(System.Nullable<int> value);
    partial void OnhouseIdChanged();
    partial void OnstepChanging(System.Nullable<int> value);
    partial void OnstepChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OnstateChanging(System.Nullable<int> value);
    partial void OnstateChanged();
    #endregion
	
	public REF_USER_HOUSEINFO()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int refId
	{
		get
		{
			return this._refId;
		}
		set
		{
			if ((this._refId != value))
			{
				this.OnrefIdChanging(value);
				this.SendPropertyChanging();
				this._refId = value;
				this.SendPropertyChanged("refId");
				this.OnrefIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int")]
	public System.Nullable<int> userId
	{
		get
		{
			return this._userId;
		}
		set
		{
			if ((this._userId != value))
			{
				this.OnuserIdChanging(value);
				this.SendPropertyChanging();
				this._userId = value;
				this.SendPropertyChanged("userId");
				this.OnuserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_houseId", DbType="Int")]
	public System.Nullable<int> houseId
	{
		get
		{
			return this._houseId;
		}
		set
		{
			if ((this._houseId != value))
			{
				this.OnhouseIdChanging(value);
				this.SendPropertyChanging();
				this._houseId = value;
				this.SendPropertyChanged("houseId");
				this.OnhouseIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_step", DbType="Int")]
	public System.Nullable<int> step
	{
		get
		{
			return this._step;
		}
		set
		{
			if ((this._step != value))
			{
				this.OnstepChanging(value);
				this.SendPropertyChanging();
				this._step = value;
				this.SendPropertyChanged("step");
				this.OnstepChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
	public System.Nullable<int> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
	public System.Nullable<int> state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOUSE_INFO")]
public partial class HOUSE_INFO : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _houseId;
	
	private System.Nullable<int> _hostId;
	
	private System.Nullable<int> _style;
	
	private System.Nullable<int> _limit;
	
	private string _houseName;
	
	private string _houseDescription;
	
	private string _city;
	
	private string _province;
	
	private string _street;
	
	private string _equipment;
	
	private string _photo;
	
	private string _safty;
	
	private string _startDate;
	
	private string _endDate;
	
	private System.Nullable<int> _type;
	
	private System.Nullable<int> _bedroom;
	
	private System.Nullable<int> _bed;
	
	private System.Nullable<int> _restroom;
	
	private string _postCode;
	
	private string _department;
	
	private System.Nullable<int> _must;
	
	private System.Nullable<int> _TV;
	
	private System.Nullable<int> _airCondition;
	
	private System.Nullable<int> _kiction;
	
	private System.Nullable<int> _network;
	
	private System.Nullable<int> _wifi;
	
	private System.Nullable<int> _time;
	
	private System.Nullable<int> _bath;
	
	private System.Nullable<int> _wash;
	
	private System.Nullable<int> _swimmingPool;
	
	private System.Nullable<int> _breakfast;
	
	private System.Nullable<int> _carPark;
	
	private System.Nullable<int> _workout;
	
	private System.Nullable<int> _lift;
	
	private System.Nullable<int> _guard;
	
	private System.Nullable<int> _children;
	
	private System.Nullable<int> _smoke;
	
	private System.Nullable<int> _party;
	
	private System.Nullable<int> _pet;
	
	private System.Nullable<int> _disable;
	
	private System.Nullable<int> _smokeAlert;
	
	private System.Nullable<int> _coAlert;
	
	private System.Nullable<int> _aid;
	
	private System.Nullable<int> _aidCard;
	
	private System.Nullable<int> _fire;
	
	private System.Nullable<int> _lock;
	
	private string _fireLocation;
	
	private string _fireAlertLocation;
	
	private string _coEnd;
	
	private string _exitLocation;
	
	private string _aidCall;
	
	private string _fireCall;
	
	private string _policeCall;
	
	private string _price;
	
	private string _cellphone;
	
	private string _weixin;
	
	private System.Nullable<int> _passState;
	
	private System.Nullable<decimal> _lat;
	
	private System.Nullable<decimal> _lng;
	
	private System.Nullable<int> _foodGuide;
	
	private System.Nullable<int> _shopGuide;
	
	private System.Nullable<int> _spotGuide;
	
	private System.Nullable<int> _translate;
	
	private System.Nullable<int> _ticket;
	
	private System.Nullable<int> _foodMake;
	
	private System.Nullable<int> _brorrowCar;
	
	private System.Nullable<int> _engage;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnhouseIdChanging(int value);
    partial void OnhouseIdChanged();
    partial void OnhostIdChanging(System.Nullable<int> value);
    partial void OnhostIdChanged();
    partial void OnstyleChanging(System.Nullable<int> value);
    partial void OnstyleChanged();
    partial void OnlimitChanging(System.Nullable<int> value);
    partial void OnlimitChanged();
    partial void OnhouseNameChanging(string value);
    partial void OnhouseNameChanged();
    partial void OnhouseDescriptionChanging(string value);
    partial void OnhouseDescriptionChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OnstreetChanging(string value);
    partial void OnstreetChanged();
    partial void OnequipmentChanging(string value);
    partial void OnequipmentChanged();
    partial void OnphotoChanging(string value);
    partial void OnphotoChanged();
    partial void OnsaftyChanging(string value);
    partial void OnsaftyChanged();
    partial void OnstartDateChanging(string value);
    partial void OnstartDateChanged();
    partial void OnendDateChanging(string value);
    partial void OnendDateChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OnbedroomChanging(System.Nullable<int> value);
    partial void OnbedroomChanged();
    partial void OnbedChanging(System.Nullable<int> value);
    partial void OnbedChanged();
    partial void OnrestroomChanging(System.Nullable<int> value);
    partial void OnrestroomChanged();
    partial void OnpostCodeChanging(string value);
    partial void OnpostCodeChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OnmustChanging(System.Nullable<int> value);
    partial void OnmustChanged();
    partial void OnTVChanging(System.Nullable<int> value);
    partial void OnTVChanged();
    partial void OnairConditionChanging(System.Nullable<int> value);
    partial void OnairConditionChanged();
    partial void OnkictionChanging(System.Nullable<int> value);
    partial void OnkictionChanged();
    partial void OnnetworkChanging(System.Nullable<int> value);
    partial void OnnetworkChanged();
    partial void OnwifiChanging(System.Nullable<int> value);
    partial void OnwifiChanged();
    partial void OntimeChanging(System.Nullable<int> value);
    partial void OntimeChanged();
    partial void OnbathChanging(System.Nullable<int> value);
    partial void OnbathChanged();
    partial void OnwashChanging(System.Nullable<int> value);
    partial void OnwashChanged();
    partial void OnswimmingPoolChanging(System.Nullable<int> value);
    partial void OnswimmingPoolChanged();
    partial void OnbreakfastChanging(System.Nullable<int> value);
    partial void OnbreakfastChanged();
    partial void OncarParkChanging(System.Nullable<int> value);
    partial void OncarParkChanged();
    partial void OnworkoutChanging(System.Nullable<int> value);
    partial void OnworkoutChanged();
    partial void OnliftChanging(System.Nullable<int> value);
    partial void OnliftChanged();
    partial void OnguardChanging(System.Nullable<int> value);
    partial void OnguardChanged();
    partial void OnchildrenChanging(System.Nullable<int> value);
    partial void OnchildrenChanged();
    partial void OnsmokeChanging(System.Nullable<int> value);
    partial void OnsmokeChanged();
    partial void OnpartyChanging(System.Nullable<int> value);
    partial void OnpartyChanged();
    partial void OnpetChanging(System.Nullable<int> value);
    partial void OnpetChanged();
    partial void OndisableChanging(System.Nullable<int> value);
    partial void OndisableChanged();
    partial void OnsmokeAlertChanging(System.Nullable<int> value);
    partial void OnsmokeAlertChanged();
    partial void OncoAlertChanging(System.Nullable<int> value);
    partial void OncoAlertChanged();
    partial void OnaidChanging(System.Nullable<int> value);
    partial void OnaidChanged();
    partial void OnaidCardChanging(System.Nullable<int> value);
    partial void OnaidCardChanged();
    partial void OnfireChanging(System.Nullable<int> value);
    partial void OnfireChanged();
    partial void OnlockChanging(System.Nullable<int> value);
    partial void OnlockChanged();
    partial void OnfireLocationChanging(string value);
    partial void OnfireLocationChanged();
    partial void OnfireAlertLocationChanging(string value);
    partial void OnfireAlertLocationChanged();
    partial void OncoEndChanging(string value);
    partial void OncoEndChanged();
    partial void OnexitLocationChanging(string value);
    partial void OnexitLocationChanged();
    partial void OnaidCallChanging(string value);
    partial void OnaidCallChanged();
    partial void OnfireCallChanging(string value);
    partial void OnfireCallChanged();
    partial void OnpoliceCallChanging(string value);
    partial void OnpoliceCallChanged();
    partial void OnpriceChanging(string value);
    partial void OnpriceChanged();
    partial void OncellphoneChanging(string value);
    partial void OncellphoneChanged();
    partial void OnweixinChanging(string value);
    partial void OnweixinChanged();
    partial void OnpassStateChanging(System.Nullable<int> value);
    partial void OnpassStateChanged();
    partial void OnlatChanging(System.Nullable<decimal> value);
    partial void OnlatChanged();
    partial void OnlngChanging(System.Nullable<decimal> value);
    partial void OnlngChanged();
    partial void OnfoodGuideChanging(System.Nullable<int> value);
    partial void OnfoodGuideChanged();
    partial void OnshopGuideChanging(System.Nullable<int> value);
    partial void OnshopGuideChanged();
    partial void OnspotGuideChanging(System.Nullable<int> value);
    partial void OnspotGuideChanged();
    partial void OntranslateChanging(System.Nullable<int> value);
    partial void OntranslateChanged();
    partial void OnticketChanging(System.Nullable<int> value);
    partial void OnticketChanged();
    partial void OnfoodMakeChanging(System.Nullable<int> value);
    partial void OnfoodMakeChanged();
    partial void OnbrorrowCarChanging(System.Nullable<int> value);
    partial void OnbrorrowCarChanged();
    partial void OnengageChanging(System.Nullable<int> value);
    partial void OnengageChanged();
    #endregion
	
	public HOUSE_INFO()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_houseId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int houseId
	{
		get
		{
			return this._houseId;
		}
		set
		{
			if ((this._houseId != value))
			{
				this.OnhouseIdChanging(value);
				this.SendPropertyChanging();
				this._houseId = value;
				this.SendPropertyChanged("houseId");
				this.OnhouseIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostId", DbType="Int")]
	public System.Nullable<int> hostId
	{
		get
		{
			return this._hostId;
		}
		set
		{
			if ((this._hostId != value))
			{
				this.OnhostIdChanging(value);
				this.SendPropertyChanging();
				this._hostId = value;
				this.SendPropertyChanged("hostId");
				this.OnhostIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_style", DbType="Int")]
	public System.Nullable<int> style
	{
		get
		{
			return this._style;
		}
		set
		{
			if ((this._style != value))
			{
				this.OnstyleChanging(value);
				this.SendPropertyChanging();
				this._style = value;
				this.SendPropertyChanged("style");
				this.OnstyleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_limit", DbType="Int")]
	public System.Nullable<int> limit
	{
		get
		{
			return this._limit;
		}
		set
		{
			if ((this._limit != value))
			{
				this.OnlimitChanging(value);
				this.SendPropertyChanging();
				this._limit = value;
				this.SendPropertyChanged("limit");
				this.OnlimitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_houseName", DbType="VarChar(MAX)")]
	public string houseName
	{
		get
		{
			return this._houseName;
		}
		set
		{
			if ((this._houseName != value))
			{
				this.OnhouseNameChanging(value);
				this.SendPropertyChanging();
				this._houseName = value;
				this.SendPropertyChanged("houseName");
				this.OnhouseNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_houseDescription", DbType="VarChar(MAX)")]
	public string houseDescription
	{
		get
		{
			return this._houseDescription;
		}
		set
		{
			if ((this._houseDescription != value))
			{
				this.OnhouseDescriptionChanging(value);
				this.SendPropertyChanging();
				this._houseDescription = value;
				this.SendPropertyChanged("houseDescription");
				this.OnhouseDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(MAX)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(MAX)")]
	public string province
	{
		get
		{
			return this._province;
		}
		set
		{
			if ((this._province != value))
			{
				this.OnprovinceChanging(value);
				this.SendPropertyChanging();
				this._province = value;
				this.SendPropertyChanged("province");
				this.OnprovinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="VarChar(MAX)")]
	public string street
	{
		get
		{
			return this._street;
		}
		set
		{
			if ((this._street != value))
			{
				this.OnstreetChanging(value);
				this.SendPropertyChanging();
				this._street = value;
				this.SendPropertyChanged("street");
				this.OnstreetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipment", DbType="VarChar(MAX)")]
	public string equipment
	{
		get
		{
			return this._equipment;
		}
		set
		{
			if ((this._equipment != value))
			{
				this.OnequipmentChanging(value);
				this.SendPropertyChanging();
				this._equipment = value;
				this.SendPropertyChanged("equipment");
				this.OnequipmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="VarChar(MAX)")]
	public string photo
	{
		get
		{
			return this._photo;
		}
		set
		{
			if ((this._photo != value))
			{
				this.OnphotoChanging(value);
				this.SendPropertyChanging();
				this._photo = value;
				this.SendPropertyChanged("photo");
				this.OnphotoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_safty", DbType="VarChar(MAX)")]
	public string safty
	{
		get
		{
			return this._safty;
		}
		set
		{
			if ((this._safty != value))
			{
				this.OnsaftyChanging(value);
				this.SendPropertyChanging();
				this._safty = value;
				this.SendPropertyChanged("safty");
				this.OnsaftyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="VarChar(50)")]
	public string startDate
	{
		get
		{
			return this._startDate;
		}
		set
		{
			if ((this._startDate != value))
			{
				this.OnstartDateChanging(value);
				this.SendPropertyChanging();
				this._startDate = value;
				this.SendPropertyChanged("startDate");
				this.OnstartDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="VarChar(50)")]
	public string endDate
	{
		get
		{
			return this._endDate;
		}
		set
		{
			if ((this._endDate != value))
			{
				this.OnendDateChanging(value);
				this.SendPropertyChanging();
				this._endDate = value;
				this.SendPropertyChanged("endDate");
				this.OnendDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
	public System.Nullable<int> type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedroom", DbType="Int")]
	public System.Nullable<int> bedroom
	{
		get
		{
			return this._bedroom;
		}
		set
		{
			if ((this._bedroom != value))
			{
				this.OnbedroomChanging(value);
				this.SendPropertyChanging();
				this._bedroom = value;
				this.SendPropertyChanged("bedroom");
				this.OnbedroomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bed", DbType="Int")]
	public System.Nullable<int> bed
	{
		get
		{
			return this._bed;
		}
		set
		{
			if ((this._bed != value))
			{
				this.OnbedChanging(value);
				this.SendPropertyChanging();
				this._bed = value;
				this.SendPropertyChanged("bed");
				this.OnbedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_restroom", DbType="Int")]
	public System.Nullable<int> restroom
	{
		get
		{
			return this._restroom;
		}
		set
		{
			if ((this._restroom != value))
			{
				this.OnrestroomChanging(value);
				this.SendPropertyChanging();
				this._restroom = value;
				this.SendPropertyChanged("restroom");
				this.OnrestroomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postCode", DbType="VarChar(MAX)")]
	public string postCode
	{
		get
		{
			return this._postCode;
		}
		set
		{
			if ((this._postCode != value))
			{
				this.OnpostCodeChanging(value);
				this.SendPropertyChanging();
				this._postCode = value;
				this.SendPropertyChanged("postCode");
				this.OnpostCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(MAX)")]
	public string department
	{
		get
		{
			return this._department;
		}
		set
		{
			if ((this._department != value))
			{
				this.OndepartmentChanging(value);
				this.SendPropertyChanging();
				this._department = value;
				this.SendPropertyChanged("department");
				this.OndepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_must", DbType="Int")]
	public System.Nullable<int> must
	{
		get
		{
			return this._must;
		}
		set
		{
			if ((this._must != value))
			{
				this.OnmustChanging(value);
				this.SendPropertyChanging();
				this._must = value;
				this.SendPropertyChanged("must");
				this.OnmustChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TV", DbType="Int")]
	public System.Nullable<int> TV
	{
		get
		{
			return this._TV;
		}
		set
		{
			if ((this._TV != value))
			{
				this.OnTVChanging(value);
				this.SendPropertyChanging();
				this._TV = value;
				this.SendPropertyChanged("TV");
				this.OnTVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_airCondition", DbType="Int")]
	public System.Nullable<int> airCondition
	{
		get
		{
			return this._airCondition;
		}
		set
		{
			if ((this._airCondition != value))
			{
				this.OnairConditionChanging(value);
				this.SendPropertyChanging();
				this._airCondition = value;
				this.SendPropertyChanged("airCondition");
				this.OnairConditionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kiction", DbType="Int")]
	public System.Nullable<int> kiction
	{
		get
		{
			return this._kiction;
		}
		set
		{
			if ((this._kiction != value))
			{
				this.OnkictionChanging(value);
				this.SendPropertyChanging();
				this._kiction = value;
				this.SendPropertyChanged("kiction");
				this.OnkictionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_network", DbType="Int")]
	public System.Nullable<int> network
	{
		get
		{
			return this._network;
		}
		set
		{
			if ((this._network != value))
			{
				this.OnnetworkChanging(value);
				this.SendPropertyChanging();
				this._network = value;
				this.SendPropertyChanged("network");
				this.OnnetworkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wifi", DbType="Int")]
	public System.Nullable<int> wifi
	{
		get
		{
			return this._wifi;
		}
		set
		{
			if ((this._wifi != value))
			{
				this.OnwifiChanging(value);
				this.SendPropertyChanging();
				this._wifi = value;
				this.SendPropertyChanged("wifi");
				this.OnwifiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Int")]
	public System.Nullable<int> time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this.OntimeChanging(value);
				this.SendPropertyChanging();
				this._time = value;
				this.SendPropertyChanged("time");
				this.OntimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bath", DbType="Int")]
	public System.Nullable<int> bath
	{
		get
		{
			return this._bath;
		}
		set
		{
			if ((this._bath != value))
			{
				this.OnbathChanging(value);
				this.SendPropertyChanging();
				this._bath = value;
				this.SendPropertyChanged("bath");
				this.OnbathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wash", DbType="Int")]
	public System.Nullable<int> wash
	{
		get
		{
			return this._wash;
		}
		set
		{
			if ((this._wash != value))
			{
				this.OnwashChanging(value);
				this.SendPropertyChanging();
				this._wash = value;
				this.SendPropertyChanged("wash");
				this.OnwashChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swimmingPool", DbType="Int")]
	public System.Nullable<int> swimmingPool
	{
		get
		{
			return this._swimmingPool;
		}
		set
		{
			if ((this._swimmingPool != value))
			{
				this.OnswimmingPoolChanging(value);
				this.SendPropertyChanging();
				this._swimmingPool = value;
				this.SendPropertyChanged("swimmingPool");
				this.OnswimmingPoolChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_breakfast", DbType="Int")]
	public System.Nullable<int> breakfast
	{
		get
		{
			return this._breakfast;
		}
		set
		{
			if ((this._breakfast != value))
			{
				this.OnbreakfastChanging(value);
				this.SendPropertyChanging();
				this._breakfast = value;
				this.SendPropertyChanged("breakfast");
				this.OnbreakfastChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carPark", DbType="Int")]
	public System.Nullable<int> carPark
	{
		get
		{
			return this._carPark;
		}
		set
		{
			if ((this._carPark != value))
			{
				this.OncarParkChanging(value);
				this.SendPropertyChanging();
				this._carPark = value;
				this.SendPropertyChanged("carPark");
				this.OncarParkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workout", DbType="Int")]
	public System.Nullable<int> workout
	{
		get
		{
			return this._workout;
		}
		set
		{
			if ((this._workout != value))
			{
				this.OnworkoutChanging(value);
				this.SendPropertyChanging();
				this._workout = value;
				this.SendPropertyChanged("workout");
				this.OnworkoutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lift", DbType="Int")]
	public System.Nullable<int> lift
	{
		get
		{
			return this._lift;
		}
		set
		{
			if ((this._lift != value))
			{
				this.OnliftChanging(value);
				this.SendPropertyChanging();
				this._lift = value;
				this.SendPropertyChanged("lift");
				this.OnliftChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guard", DbType="Int")]
	public System.Nullable<int> guard
	{
		get
		{
			return this._guard;
		}
		set
		{
			if ((this._guard != value))
			{
				this.OnguardChanging(value);
				this.SendPropertyChanging();
				this._guard = value;
				this.SendPropertyChanged("guard");
				this.OnguardChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_children", DbType="Int")]
	public System.Nullable<int> children
	{
		get
		{
			return this._children;
		}
		set
		{
			if ((this._children != value))
			{
				this.OnchildrenChanging(value);
				this.SendPropertyChanging();
				this._children = value;
				this.SendPropertyChanged("children");
				this.OnchildrenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smoke", DbType="Int")]
	public System.Nullable<int> smoke
	{
		get
		{
			return this._smoke;
		}
		set
		{
			if ((this._smoke != value))
			{
				this.OnsmokeChanging(value);
				this.SendPropertyChanging();
				this._smoke = value;
				this.SendPropertyChanged("smoke");
				this.OnsmokeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_party", DbType="Int")]
	public System.Nullable<int> party
	{
		get
		{
			return this._party;
		}
		set
		{
			if ((this._party != value))
			{
				this.OnpartyChanging(value);
				this.SendPropertyChanging();
				this._party = value;
				this.SendPropertyChanged("party");
				this.OnpartyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pet", DbType="Int")]
	public System.Nullable<int> pet
	{
		get
		{
			return this._pet;
		}
		set
		{
			if ((this._pet != value))
			{
				this.OnpetChanging(value);
				this.SendPropertyChanging();
				this._pet = value;
				this.SendPropertyChanged("pet");
				this.OnpetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disable", DbType="Int")]
	public System.Nullable<int> disable
	{
		get
		{
			return this._disable;
		}
		set
		{
			if ((this._disable != value))
			{
				this.OndisableChanging(value);
				this.SendPropertyChanging();
				this._disable = value;
				this.SendPropertyChanged("disable");
				this.OndisableChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smokeAlert", DbType="Int")]
	public System.Nullable<int> smokeAlert
	{
		get
		{
			return this._smokeAlert;
		}
		set
		{
			if ((this._smokeAlert != value))
			{
				this.OnsmokeAlertChanging(value);
				this.SendPropertyChanging();
				this._smokeAlert = value;
				this.SendPropertyChanged("smokeAlert");
				this.OnsmokeAlertChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coAlert", DbType="Int")]
	public System.Nullable<int> coAlert
	{
		get
		{
			return this._coAlert;
		}
		set
		{
			if ((this._coAlert != value))
			{
				this.OncoAlertChanging(value);
				this.SendPropertyChanging();
				this._coAlert = value;
				this.SendPropertyChanged("coAlert");
				this.OncoAlertChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aid", DbType="Int")]
	public System.Nullable<int> aid
	{
		get
		{
			return this._aid;
		}
		set
		{
			if ((this._aid != value))
			{
				this.OnaidChanging(value);
				this.SendPropertyChanging();
				this._aid = value;
				this.SendPropertyChanged("aid");
				this.OnaidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aidCard", DbType="Int")]
	public System.Nullable<int> aidCard
	{
		get
		{
			return this._aidCard;
		}
		set
		{
			if ((this._aidCard != value))
			{
				this.OnaidCardChanging(value);
				this.SendPropertyChanging();
				this._aidCard = value;
				this.SendPropertyChanged("aidCard");
				this.OnaidCardChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fire", DbType="Int")]
	public System.Nullable<int> fire
	{
		get
		{
			return this._fire;
		}
		set
		{
			if ((this._fire != value))
			{
				this.OnfireChanging(value);
				this.SendPropertyChanging();
				this._fire = value;
				this.SendPropertyChanged("fire");
				this.OnfireChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="lock", Storage="_lock", DbType="Int")]
	public System.Nullable<int> @lock
	{
		get
		{
			return this._lock;
		}
		set
		{
			if ((this._lock != value))
			{
				this.OnlockChanging(value);
				this.SendPropertyChanging();
				this._lock = value;
				this.SendPropertyChanged("@lock");
				this.OnlockChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fireLocation", DbType="VarChar(MAX)")]
	public string fireLocation
	{
		get
		{
			return this._fireLocation;
		}
		set
		{
			if ((this._fireLocation != value))
			{
				this.OnfireLocationChanging(value);
				this.SendPropertyChanging();
				this._fireLocation = value;
				this.SendPropertyChanged("fireLocation");
				this.OnfireLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fireAlertLocation", DbType="VarChar(MAX)")]
	public string fireAlertLocation
	{
		get
		{
			return this._fireAlertLocation;
		}
		set
		{
			if ((this._fireAlertLocation != value))
			{
				this.OnfireAlertLocationChanging(value);
				this.SendPropertyChanging();
				this._fireAlertLocation = value;
				this.SendPropertyChanged("fireAlertLocation");
				this.OnfireAlertLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coEnd", DbType="VarChar(MAX)")]
	public string coEnd
	{
		get
		{
			return this._coEnd;
		}
		set
		{
			if ((this._coEnd != value))
			{
				this.OncoEndChanging(value);
				this.SendPropertyChanging();
				this._coEnd = value;
				this.SendPropertyChanged("coEnd");
				this.OncoEndChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exitLocation", DbType="VarChar(MAX)")]
	public string exitLocation
	{
		get
		{
			return this._exitLocation;
		}
		set
		{
			if ((this._exitLocation != value))
			{
				this.OnexitLocationChanging(value);
				this.SendPropertyChanging();
				this._exitLocation = value;
				this.SendPropertyChanged("exitLocation");
				this.OnexitLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aidCall", DbType="VarChar(MAX)")]
	public string aidCall
	{
		get
		{
			return this._aidCall;
		}
		set
		{
			if ((this._aidCall != value))
			{
				this.OnaidCallChanging(value);
				this.SendPropertyChanging();
				this._aidCall = value;
				this.SendPropertyChanged("aidCall");
				this.OnaidCallChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fireCall", DbType="VarChar(MAX)")]
	public string fireCall
	{
		get
		{
			return this._fireCall;
		}
		set
		{
			if ((this._fireCall != value))
			{
				this.OnfireCallChanging(value);
				this.SendPropertyChanging();
				this._fireCall = value;
				this.SendPropertyChanged("fireCall");
				this.OnfireCallChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_policeCall", DbType="VarChar(MAX)")]
	public string policeCall
	{
		get
		{
			return this._policeCall;
		}
		set
		{
			if ((this._policeCall != value))
			{
				this.OnpoliceCallChanging(value);
				this.SendPropertyChanging();
				this._policeCall = value;
				this.SendPropertyChanged("policeCall");
				this.OnpoliceCallChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="VarChar(MAX)")]
	public string price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cellphone", DbType="VarChar(MAX)")]
	public string cellphone
	{
		get
		{
			return this._cellphone;
		}
		set
		{
			if ((this._cellphone != value))
			{
				this.OncellphoneChanging(value);
				this.SendPropertyChanging();
				this._cellphone = value;
				this.SendPropertyChanged("cellphone");
				this.OncellphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weixin", DbType="VarChar(MAX)")]
	public string weixin
	{
		get
		{
			return this._weixin;
		}
		set
		{
			if ((this._weixin != value))
			{
				this.OnweixinChanging(value);
				this.SendPropertyChanging();
				this._weixin = value;
				this.SendPropertyChanged("weixin");
				this.OnweixinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passState", DbType="Int")]
	public System.Nullable<int> passState
	{
		get
		{
			return this._passState;
		}
		set
		{
			if ((this._passState != value))
			{
				this.OnpassStateChanging(value);
				this.SendPropertyChanging();
				this._passState = value;
				this.SendPropertyChanged("passState");
				this.OnpassStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="Decimal(20,17)")]
	public System.Nullable<decimal> lat
	{
		get
		{
			return this._lat;
		}
		set
		{
			if ((this._lat != value))
			{
				this.OnlatChanging(value);
				this.SendPropertyChanging();
				this._lat = value;
				this.SendPropertyChanged("lat");
				this.OnlatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lng", DbType="Decimal(20,17)")]
	public System.Nullable<decimal> lng
	{
		get
		{
			return this._lng;
		}
		set
		{
			if ((this._lng != value))
			{
				this.OnlngChanging(value);
				this.SendPropertyChanging();
				this._lng = value;
				this.SendPropertyChanged("lng");
				this.OnlngChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foodGuide", DbType="Int")]
	public System.Nullable<int> foodGuide
	{
		get
		{
			return this._foodGuide;
		}
		set
		{
			if ((this._foodGuide != value))
			{
				this.OnfoodGuideChanging(value);
				this.SendPropertyChanging();
				this._foodGuide = value;
				this.SendPropertyChanged("foodGuide");
				this.OnfoodGuideChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shopGuide", DbType="Int")]
	public System.Nullable<int> shopGuide
	{
		get
		{
			return this._shopGuide;
		}
		set
		{
			if ((this._shopGuide != value))
			{
				this.OnshopGuideChanging(value);
				this.SendPropertyChanging();
				this._shopGuide = value;
				this.SendPropertyChanged("shopGuide");
				this.OnshopGuideChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spotGuide", DbType="Int")]
	public System.Nullable<int> spotGuide
	{
		get
		{
			return this._spotGuide;
		}
		set
		{
			if ((this._spotGuide != value))
			{
				this.OnspotGuideChanging(value);
				this.SendPropertyChanging();
				this._spotGuide = value;
				this.SendPropertyChanged("spotGuide");
				this.OnspotGuideChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_translate", DbType="Int")]
	public System.Nullable<int> translate
	{
		get
		{
			return this._translate;
		}
		set
		{
			if ((this._translate != value))
			{
				this.OntranslateChanging(value);
				this.SendPropertyChanging();
				this._translate = value;
				this.SendPropertyChanged("translate");
				this.OntranslateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ticket", DbType="Int")]
	public System.Nullable<int> ticket
	{
		get
		{
			return this._ticket;
		}
		set
		{
			if ((this._ticket != value))
			{
				this.OnticketChanging(value);
				this.SendPropertyChanging();
				this._ticket = value;
				this.SendPropertyChanged("ticket");
				this.OnticketChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foodMake", DbType="Int")]
	public System.Nullable<int> foodMake
	{
		get
		{
			return this._foodMake;
		}
		set
		{
			if ((this._foodMake != value))
			{
				this.OnfoodMakeChanging(value);
				this.SendPropertyChanging();
				this._foodMake = value;
				this.SendPropertyChanged("foodMake");
				this.OnfoodMakeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brorrowCar", DbType="Int")]
	public System.Nullable<int> brorrowCar
	{
		get
		{
			return this._brorrowCar;
		}
		set
		{
			if ((this._brorrowCar != value))
			{
				this.OnbrorrowCarChanging(value);
				this.SendPropertyChanging();
				this._brorrowCar = value;
				this.SendPropertyChanged("brorrowCar");
				this.OnbrorrowCarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_engage", DbType="Int")]
	public System.Nullable<int> engage
	{
		get
		{
			return this._engage;
		}
		set
		{
			if ((this._engage != value))
			{
				this.OnengageChanging(value);
				this.SendPropertyChanging();
				this._engage = value;
				this.SendPropertyChanged("engage");
				this.OnengageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMMENT")]
public partial class COMMENT : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _commentId;
	
	private int _houseId;
	
	private string _commentContent;
	
	private int _userId;
	
	private string _commentDate;
	
	private int _star;
	
	private string _photo;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncommentIdChanging(int value);
    partial void OncommentIdChanged();
    partial void OnhouseIdChanging(int value);
    partial void OnhouseIdChanged();
    partial void OncommentContentChanging(string value);
    partial void OncommentContentChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OncommentDateChanging(string value);
    partial void OncommentDateChanged();
    partial void OnstarChanging(int value);
    partial void OnstarChanged();
    partial void OnphotoChanging(string value);
    partial void OnphotoChanged();
    #endregion
	
	public COMMENT()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int commentId
	{
		get
		{
			return this._commentId;
		}
		set
		{
			if ((this._commentId != value))
			{
				this.OncommentIdChanging(value);
				this.SendPropertyChanging();
				this._commentId = value;
				this.SendPropertyChanged("commentId");
				this.OncommentIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_houseId", DbType="Int NOT NULL")]
	public int houseId
	{
		get
		{
			return this._houseId;
		}
		set
		{
			if ((this._houseId != value))
			{
				this.OnhouseIdChanging(value);
				this.SendPropertyChanging();
				this._houseId = value;
				this.SendPropertyChanged("houseId");
				this.OnhouseIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentContent", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string commentContent
	{
		get
		{
			return this._commentContent;
		}
		set
		{
			if ((this._commentContent != value))
			{
				this.OncommentContentChanging(value);
				this.SendPropertyChanging();
				this._commentContent = value;
				this.SendPropertyChanged("commentContent");
				this.OncommentContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
	public int userId
	{
		get
		{
			return this._userId;
		}
		set
		{
			if ((this._userId != value))
			{
				this.OnuserIdChanging(value);
				this.SendPropertyChanging();
				this._userId = value;
				this.SendPropertyChanged("userId");
				this.OnuserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentDate", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string commentDate
	{
		get
		{
			return this._commentDate;
		}
		set
		{
			if ((this._commentDate != value))
			{
				this.OncommentDateChanging(value);
				this.SendPropertyChanging();
				this._commentDate = value;
				this.SendPropertyChanged("commentDate");
				this.OncommentDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_star", DbType="Int NOT NULL")]
	public int star
	{
		get
		{
			return this._star;
		}
		set
		{
			if ((this._star != value))
			{
				this.OnstarChanging(value);
				this.SendPropertyChanging();
				this._star = value;
				this.SendPropertyChanged("star");
				this.OnstarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="VarChar(MAX)")]
	public string photo
	{
		get
		{
			return this._photo;
		}
		set
		{
			if ((this._photo != value))
			{
				this.OnphotoChanging(value);
				this.SendPropertyChanging();
				this._photo = value;
				this.SendPropertyChanged("photo");
				this.OnphotoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COLLECCTION")]
public partial class COLLECCTION : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _collectionId;
	
	private int _houseId;
	
	private int _userId;
	
	private string _housePic;
	
	private string _houseName;
	
	private string _startDate;
	
	private string _endDate;
	
	private int _price;
	
	private string _province;
	
	private string _city;
	
	private System.Nullable<decimal> _lat;
	
	private System.Nullable<decimal> _lng;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncollectionIdChanging(int value);
    partial void OncollectionIdChanged();
    partial void OnhouseIdChanging(int value);
    partial void OnhouseIdChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OnhousePicChanging(string value);
    partial void OnhousePicChanged();
    partial void OnhouseNameChanging(string value);
    partial void OnhouseNameChanged();
    partial void OnstartDateChanging(string value);
    partial void OnstartDateChanged();
    partial void OnendDateChanging(string value);
    partial void OnendDateChanged();
    partial void OnpriceChanging(int value);
    partial void OnpriceChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnlatChanging(System.Nullable<decimal> value);
    partial void OnlatChanged();
    partial void OnlngChanging(System.Nullable<decimal> value);
    partial void OnlngChanged();
    #endregion
	
	public COLLECCTION()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collectionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int collectionId
	{
		get
		{
			return this._collectionId;
		}
		set
		{
			if ((this._collectionId != value))
			{
				this.OncollectionIdChanging(value);
				this.SendPropertyChanging();
				this._collectionId = value;
				this.SendPropertyChanged("collectionId");
				this.OncollectionIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_houseId", DbType="Int NOT NULL")]
	public int houseId
	{
		get
		{
			return this._houseId;
		}
		set
		{
			if ((this._houseId != value))
			{
				this.OnhouseIdChanging(value);
				this.SendPropertyChanging();
				this._houseId = value;
				this.SendPropertyChanged("houseId");
				this.OnhouseIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
	public int userId
	{
		get
		{
			return this._userId;
		}
		set
		{
			if ((this._userId != value))
			{
				this.OnuserIdChanging(value);
				this.SendPropertyChanging();
				this._userId = value;
				this.SendPropertyChanged("userId");
				this.OnuserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_housePic", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string housePic
	{
		get
		{
			return this._housePic;
		}
		set
		{
			if ((this._housePic != value))
			{
				this.OnhousePicChanging(value);
				this.SendPropertyChanging();
				this._housePic = value;
				this.SendPropertyChanged("housePic");
				this.OnhousePicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_houseName", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string houseName
	{
		get
		{
			return this._houseName;
		}
		set
		{
			if ((this._houseName != value))
			{
				this.OnhouseNameChanging(value);
				this.SendPropertyChanging();
				this._houseName = value;
				this.SendPropertyChanged("houseName");
				this.OnhouseNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string startDate
	{
		get
		{
			return this._startDate;
		}
		set
		{
			if ((this._startDate != value))
			{
				this.OnstartDateChanging(value);
				this.SendPropertyChanging();
				this._startDate = value;
				this.SendPropertyChanged("startDate");
				this.OnstartDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string endDate
	{
		get
		{
			return this._endDate;
		}
		set
		{
			if ((this._endDate != value))
			{
				this.OnendDateChanging(value);
				this.SendPropertyChanging();
				this._endDate = value;
				this.SendPropertyChanged("endDate");
				this.OnendDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int NOT NULL")]
	public int price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(MAX)")]
	public string province
	{
		get
		{
			return this._province;
		}
		set
		{
			if ((this._province != value))
			{
				this.OnprovinceChanging(value);
				this.SendPropertyChanging();
				this._province = value;
				this.SendPropertyChanged("province");
				this.OnprovinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(MAX)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="Decimal(20,17)")]
	public System.Nullable<decimal> lat
	{
		get
		{
			return this._lat;
		}
		set
		{
			if ((this._lat != value))
			{
				this.OnlatChanging(value);
				this.SendPropertyChanging();
				this._lat = value;
				this.SendPropertyChanged("lat");
				this.OnlatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lng", DbType="Decimal(20,17)")]
	public System.Nullable<decimal> lng
	{
		get
		{
			return this._lng;
		}
		set
		{
			if ((this._lng != value))
			{
				this.OnlngChanging(value);
				this.SendPropertyChanging();
				this._lng = value;
				this.SendPropertyChanged("lng");
				this.OnlngChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOUSE_ORDER")]
public partial class HOUSE_ORDER : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _orderId;
	
	private int _hostId;
	
	private int _customerId;
	
	private int _houseId;
	
	private string _orderDate;
	
	private int _state;
	
	private int _price;
	
	private string _startDate;
	
	private string _endDate;
	
	private string _houseName;
	
	private string _housePic;
	
	private string _stateHintCustomer;
	
	private string _stateNameCustomer;
	
	private string _stateNameHost;
	
	private System.Nullable<int> _isShowCustomer;
	
	private System.Nullable<int> _isShowHost;
	
	private string _stateHintHost;
	
	private System.Nullable<int> _customerCheck;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorderIdChanging(int value);
    partial void OnorderIdChanged();
    partial void OnhostIdChanging(int value);
    partial void OnhostIdChanged();
    partial void OncustomerIdChanging(int value);
    partial void OncustomerIdChanged();
    partial void OnhouseIdChanging(int value);
    partial void OnhouseIdChanged();
    partial void OnorderDateChanging(string value);
    partial void OnorderDateChanged();
    partial void OnstateChanging(int value);
    partial void OnstateChanged();
    partial void OnpriceChanging(int value);
    partial void OnpriceChanged();
    partial void OnstartDateChanging(string value);
    partial void OnstartDateChanged();
    partial void OnendDateChanging(string value);
    partial void OnendDateChanged();
    partial void OnhouseNameChanging(string value);
    partial void OnhouseNameChanged();
    partial void OnhousePicChanging(string value);
    partial void OnhousePicChanged();
    partial void OnstateHintCustomerChanging(string value);
    partial void OnstateHintCustomerChanged();
    partial void OnstateNameCustomerChanging(string value);
    partial void OnstateNameCustomerChanged();
    partial void OnstateNameHostChanging(string value);
    partial void OnstateNameHostChanged();
    partial void OnisShowCustomerChanging(System.Nullable<int> value);
    partial void OnisShowCustomerChanged();
    partial void OnisShowHostChanging(System.Nullable<int> value);
    partial void OnisShowHostChanged();
    partial void OnstateHintHostChanging(string value);
    partial void OnstateHintHostChanged();
    partial void OncustomerCheckChanging(System.Nullable<int> value);
    partial void OncustomerCheckChanged();
    #endregion
	
	public HOUSE_ORDER()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int orderId
	{
		get
		{
			return this._orderId;
		}
		set
		{
			if ((this._orderId != value))
			{
				this.OnorderIdChanging(value);
				this.SendPropertyChanging();
				this._orderId = value;
				this.SendPropertyChanged("orderId");
				this.OnorderIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostId", DbType="Int NOT NULL")]
	public int hostId
	{
		get
		{
			return this._hostId;
		}
		set
		{
			if ((this._hostId != value))
			{
				this.OnhostIdChanging(value);
				this.SendPropertyChanging();
				this._hostId = value;
				this.SendPropertyChanged("hostId");
				this.OnhostIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerId", DbType="Int NOT NULL")]
	public int customerId
	{
		get
		{
			return this._customerId;
		}
		set
		{
			if ((this._customerId != value))
			{
				this.OncustomerIdChanging(value);
				this.SendPropertyChanging();
				this._customerId = value;
				this.SendPropertyChanged("customerId");
				this.OncustomerIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_houseId", DbType="Int NOT NULL")]
	public int houseId
	{
		get
		{
			return this._houseId;
		}
		set
		{
			if ((this._houseId != value))
			{
				this.OnhouseIdChanging(value);
				this.SendPropertyChanging();
				this._houseId = value;
				this.SendPropertyChanged("houseId");
				this.OnhouseIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderDate", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string orderDate
	{
		get
		{
			return this._orderDate;
		}
		set
		{
			if ((this._orderDate != value))
			{
				this.OnorderDateChanging(value);
				this.SendPropertyChanging();
				this._orderDate = value;
				this.SendPropertyChanged("orderDate");
				this.OnorderDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int NOT NULL")]
	public int state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int NOT NULL")]
	public int price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string startDate
	{
		get
		{
			return this._startDate;
		}
		set
		{
			if ((this._startDate != value))
			{
				this.OnstartDateChanging(value);
				this.SendPropertyChanging();
				this._startDate = value;
				this.SendPropertyChanged("startDate");
				this.OnstartDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string endDate
	{
		get
		{
			return this._endDate;
		}
		set
		{
			if ((this._endDate != value))
			{
				this.OnendDateChanging(value);
				this.SendPropertyChanging();
				this._endDate = value;
				this.SendPropertyChanged("endDate");
				this.OnendDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_houseName", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string houseName
	{
		get
		{
			return this._houseName;
		}
		set
		{
			if ((this._houseName != value))
			{
				this.OnhouseNameChanging(value);
				this.SendPropertyChanging();
				this._houseName = value;
				this.SendPropertyChanged("houseName");
				this.OnhouseNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_housePic", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string housePic
	{
		get
		{
			return this._housePic;
		}
		set
		{
			if ((this._housePic != value))
			{
				this.OnhousePicChanging(value);
				this.SendPropertyChanging();
				this._housePic = value;
				this.SendPropertyChanged("housePic");
				this.OnhousePicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateHintCustomer", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string stateHintCustomer
	{
		get
		{
			return this._stateHintCustomer;
		}
		set
		{
			if ((this._stateHintCustomer != value))
			{
				this.OnstateHintCustomerChanging(value);
				this.SendPropertyChanging();
				this._stateHintCustomer = value;
				this.SendPropertyChanged("stateHintCustomer");
				this.OnstateHintCustomerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateNameCustomer", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string stateNameCustomer
	{
		get
		{
			return this._stateNameCustomer;
		}
		set
		{
			if ((this._stateNameCustomer != value))
			{
				this.OnstateNameCustomerChanging(value);
				this.SendPropertyChanging();
				this._stateNameCustomer = value;
				this.SendPropertyChanged("stateNameCustomer");
				this.OnstateNameCustomerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateNameHost", DbType="VarChar(MAX)")]
	public string stateNameHost
	{
		get
		{
			return this._stateNameHost;
		}
		set
		{
			if ((this._stateNameHost != value))
			{
				this.OnstateNameHostChanging(value);
				this.SendPropertyChanging();
				this._stateNameHost = value;
				this.SendPropertyChanged("stateNameHost");
				this.OnstateNameHostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isShowCustomer", DbType="Int")]
	public System.Nullable<int> isShowCustomer
	{
		get
		{
			return this._isShowCustomer;
		}
		set
		{
			if ((this._isShowCustomer != value))
			{
				this.OnisShowCustomerChanging(value);
				this.SendPropertyChanging();
				this._isShowCustomer = value;
				this.SendPropertyChanged("isShowCustomer");
				this.OnisShowCustomerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isShowHost", DbType="Int")]
	public System.Nullable<int> isShowHost
	{
		get
		{
			return this._isShowHost;
		}
		set
		{
			if ((this._isShowHost != value))
			{
				this.OnisShowHostChanging(value);
				this.SendPropertyChanging();
				this._isShowHost = value;
				this.SendPropertyChanged("isShowHost");
				this.OnisShowHostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateHintHost", DbType="VarChar(MAX)")]
	public string stateHintHost
	{
		get
		{
			return this._stateHintHost;
		}
		set
		{
			if ((this._stateHintHost != value))
			{
				this.OnstateHintHostChanging(value);
				this.SendPropertyChanging();
				this._stateHintHost = value;
				this.SendPropertyChanged("stateHintHost");
				this.OnstateHintHostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerCheck", DbType="Int")]
	public System.Nullable<int> customerCheck
	{
		get
		{
			return this._customerCheck;
		}
		set
		{
			if ((this._customerCheck != value))
			{
				this.OncustomerCheckChanging(value);
				this.SendPropertyChanging();
				this._customerCheck = value;
				this.SendPropertyChanged("customerCheck");
				this.OncustomerCheckChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
